//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public int Restaurant_Id { get; set; }
        public string Changed_By { get; set; }
        public System.DateTime Change_Date { get; set; }
        public string Genre { get; set; }
        public byte Price { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
