//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReview.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class Review
    {
        public int Review_Id { get; set; }
        public int Restaurant_Id { get; set; }
		[Required]
        public string Content { get; set; }
		[Required]
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Created_By { get; set; }
		[Required]
        public byte Rating { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
